version: '3.8'
services:
  web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       ports:
           - 8000:8000
  frontend:
    container_name: frontend
    build: ./reactapp
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
