# Generated by Django 3.1.7 on 2021-08-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210804_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=200)),
                ('color', models.IntegerField()),
                ('netplayCode', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
    ]
