# Generated by Django 3.1.7 on 2021-08-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playersessioninfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersessioninfo',
            old_name='game_id',
            new_name='game',
        ),
    ]
